name: "Close stale issues and pull requests"
runs-on: ubuntu-latest
uses: actions/stale@v3
repo-token: ${{ secrets.GITHUB_TOKEN }}
stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
stale-pr-message: 'This pull request is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days'
stale-issue-label: 'stale'
exempt-issue-labels: 'accepted'
stale-pr-label: 'stale'
exempt-pr-labels: 'accepted'
days-before-stale: 30
days-before-close: 5
